name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        run: |
         git clone https://github.com/mkdev55/cipython.git 
         cd cipython
         cat Dockerfile
         docker build -t mengkheang55/test:release-v1 . 
         docker login -u mengkheang55 -p dckr_pat_N-PjfK6Vt3wmo1FS4IrgdxX9Zag
         docker push mengkheang55/test:release-v1
         
      - name: ssh-to-server
        run: |
          ssh 
