name: deploy project to production server

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
      - name:test
         run:|
         docker build -t test:release-v1 .

      - name:push
         run:|
           docker login -u mengkheang55 -p dckr_pat_N-PjfK6Vt3wmo1FS4IrgdxX9Zag
           docker push mengkheang55/test:release-v1
    
     
